name: civicfix
description: Smart City Public Works Feedback App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  # Image + File
  image_picker: ^1.1.2
  file_picker: ^8.3.7

  # Location + Maps
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1

  # HTTP (Cloudinary)
  http: ^1.2.1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1

  # State
  provider: ^6.1.2

  # UI
  flutter_svg: ^2.0.10

  # Animations
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  confetti: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
